<?php
return [
    'title' => 'MBA Colleges in Jaipur',
    'singular' => 'MBA College',
    'program' => 'MBA / PGDM',
    'description' => 'Explore selected MBA and management institutes in Jaipur with verified official contact links and request admission guidance from Forsk Coding School.',
    'colleges' => [
        [
            'slug' => 'jaipuria-institute-of-management-jaipur',
            'name' => 'Jaipuria Institute of Management, Jaipur',
            'short' => 'Jaipuria Institute of Management Jaipur',
            'phone' => '+91 8800495724',
            'website' => 'https://www.jaipuria.ac.in/jaipur/',
            'official_page' => 'https://www.jaipuria.ac.in/jaipur/admissions/',
            'brochure' => '',
            'address' => '1, Bambala Institutional Area, Pratap Nagar, Sanganer, Jaipur 302033',
            'source' => 'https://admissionguide.jaipuria.ac.in/contactus',
            'logo_path' => 'mba-colleges-in-jaipur/assets/logos/jaipuria-institute-of-management-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'iihmr-university-jaipur',
            'name' => 'IIHMR University Jaipur',
            'short' => 'IIHMR University Jaipur',
            'phone' => '+91 1413924700',
            'website' => 'https://iihmr.edu.in/',
            'official_page' => 'https://iihmr.edu.in/admission',
            'brochure' => '',
            'address' => '1, Prabhu Dayal Marg, Near Sanganer Airport, Jaipur 302029',
            'source' => 'https://iihmr.edu.in/contact',
            'logo_path' => 'mba-colleges-in-jaipur/assets/logos/iihmr-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'manipal-university-jaipur',
            'name' => 'Manipal University Jaipur',
            'short' => 'Manipal University Jaipur',
            'phone' => '1800 102 0128',
            'website' => 'https://jaipur.manipal.edu/',
            'official_page' => 'https://jaipur.manipal.edu/admission-contact.php',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan',
            'source' => 'https://jaipur.manipal.edu/admission-contact.php',
            'logo_path' => 'mba-colleges-in-jaipur/assets/logos/manipal-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'jecrc-university',
            'name' => 'JECRC University',
            'short' => 'JECRC University',
            'phone' => '+91 9773368851',
            'website' => 'https://jecrcuniversity.edu.in/',
            'official_page' => 'https://jecrcuniversity.edu.in/',
            'brochure' => '',
            'address' => 'Ramchandrapura Industrial Area, Vidhani, Sitapura Extension, Jaipur 303905',
            'source' => 'https://jecrcuniversity.edu.in/contact-us/',
            'logo_path' => 'mba-colleges-in-jaipur/assets/logos/jecrc-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'skit-jaipur',
            'name' => 'Swami Keshvanand Institute of Technology, Management & Gramothan',
            'short' => 'SKIT Jaipur',
            'phone' => '+91 9680080686',
            'website' => 'https://www.skit.ac.in/',
            'official_page' => 'https://www.skit.ac.in/admission/mba/',
            'brochure' => '',
            'address' => 'Ramnagaria, Jagatpura, Jaipur 302017',
            'source' => 'https://www.skit.ac.in/admission/mba/',
            'logo_path' => 'mba-colleges-in-jaipur/assets/logos/skit-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
    ],
    'slug' => 'mba-colleges-in-jaipur',
];
