<?php
return [
    'title' => 'BBA Colleges in Jaipur',
    'singular' => 'BBA College',
    'program' => 'BBA',
    'description' => 'Explore selected BBA colleges and universities in Jaipur with verified official contact links and request admission guidance from Forsk Coding School.',
    'colleges' => [
        [
            'slug' => 'jecrc-university',
            'name' => 'JECRC University',
            'short' => 'JECRC University',
            'phone' => '+91 9773368851',
            'website' => 'https://jecrcuniversity.edu.in/',
            'official_page' => 'https://jecrcuniversity.edu.in/',
            'brochure' => '',
            'address' => 'Ramchandrapura Industrial Area, Vidhani, Sitapura Extension, Jaipur 303905',
            'source' => 'https://jecrcuniversity.edu.in/contact-us/',
            'logo_path' => 'bba-colleges-in-jaipur/assets/logos/jecrc-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'jaipur-national-university',
            'name' => 'Jaipur National University',
            'short' => 'Jaipur National University',
            'phone' => '1800 102 1900',
            'website' => 'https://www.jnujaipur.ac.in/',
            'official_page' => 'https://www.jnujaipur.ac.in/programmes/ug-programmes/bba-college-in-jaipur-rajasthan',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan',
            'source' => 'https://www.jnujaipur.ac.in/programmes/ug-programmes/bba-college-in-jaipur-rajasthan',
            'logo_path' => 'bba-colleges-in-jaipur/assets/logos/jaipur-national-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'manipal-university-jaipur',
            'name' => 'Manipal University Jaipur',
            'short' => 'Manipal University Jaipur',
            'phone' => '1800 102 0128',
            'website' => 'https://jaipur.manipal.edu/',
            'official_page' => 'https://jaipur.manipal.edu/admission-contact.php',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan',
            'source' => 'https://jaipur.manipal.edu/admission-contact.php',
            'logo_path' => 'bba-colleges-in-jaipur/assets/logos/manipal-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'poornima-university',
            'name' => 'Poornima University',
            'short' => 'Poornima University',
            'phone' => '+91 8875666618',
            'website' => 'https://www.poornima.edu.in/',
            'official_page' => 'https://poornima.edu.in/admissions/ug/faculty-of-management-and-commerce/bbabusiness/',
            'brochure' => '',
            'address' => 'Ramchandrapura, Vidhani Vatika, Sitapura Extension, Jaipur 303905',
            'source' => 'https://poornima.edu.in/admissions/ug/faculty-of-management-and-commerce/bbabusiness/',
            'logo_path' => 'bba-colleges-in-jaipur/assets/logos/poornima-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'iis-university-jaipur',
            'name' => 'IIS (Deemed to be University), Jaipur',
            'short' => 'IIS University Jaipur',
            'phone' => '+91 9216091144',
            'website' => 'https://www.iisuniv.ac.in/',
            'official_page' => 'https://iisuniv.ac.in/pages/bba-admission-2026.html',
            'brochure' => '',
            'address' => 'Gurukul Marg, SFS, Mansarovar, Jaipur 302020',
            'source' => 'https://iisuniv.ac.in/pages/bba-admission-2026.html',
            'logo_path' => 'bba-colleges-in-jaipur/assets/logos/iis-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
    ],
    'slug' => 'bba-colleges-in-jaipur',
];
