<?php
$root_path=dirname(__DIR__); require_once $root_path.'/config.php';
$page_title='Forsk Coding School Knowledge Hub | Practical Coding, AI & IT Guides';
$page_description='Explore curated roadmaps, projects, interview guides and practical workflows across programming, full stack, data, AI, cloud, cyber security and more.';
$page_canonical=seo_url('blog/'); $page_type='website'; $header_variant='header-1';
$page_schema=json_encode(['@context'=>'https://schema.org','@graph'=>[
 ['@type'=>'CollectionPage','name'=>$page_title,'description'=>$page_description,'url'=>$page_canonical,'isPartOf'=>['@type'=>'WebSite','@id'=>SEO_BASE_URL.'/#website']],
 ['@type'=>'BreadcrumbList','itemListElement'=>[
  ['@type'=>'ListItem','position'=>1,'name'=>'Home','item'=>SEO_BASE_URL.'/'],
  ['@type'=>'ListItem','position'=>2,'name'=>'Blog','item'=>$page_canonical]
 ]]
]],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
$data=json_decode((string)file_get_contents(__DIR__.'/blog-index.json'),true) ?: [];
$hubs=json_decode((string)file_get_contents(__DIR__.'/topic-hubs.json'),true) ?: [];

// Default archive intentionally exposes only pages approved for indexing plus legacy pages.
$data=array_values(array_filter($data,fn($e)=>($e['indexable'] ?? true)===true));
$q=trim((string)($_GET['q'] ?? '')); $category=trim((string)($_GET['category'] ?? '')); $page=max(1,(int)($_GET['page'] ?? 1)); $per=30;
if ($q!=='' || $category!=='') $data=array_values(array_filter($data,function($e)use($q,$category){$okq=$q==='' || stripos(($e['title']??'').' '.($e['description']??'').' '.($e['subject']??''),$q)!==false; $okc=$category==='' || strcasecmp($e['category']??'',$category)===0; return $okq&&$okc;}));
$total=count($data); $pages=max(1,(int)ceil($total/$per)); if($page>$pages)$page=$pages; $slice=array_slice($data,($page-1)*$per,$per);
$cats=[]; foreach($data as $e){if(!empty($e['category']))$cats[$e['category']]=true;} ksort($cats);
if($page>1 || $q!=='' || $category!=='') $page_robots='noindex, follow';
?><!doctype html><html lang="en"><head><?php include $root_path.'/includes/head.php'; ?></head><body><?php include $root_path.'/includes/header.php'; ?><div id="smooth-wrapper"><div id="smooth-content"><main id="primary" class="site-main"><div class="space-for-header"></div>
<section class="tj-page-header"><div class="container"><div class="tj-page-header-content"><h1 class="tj-page-title">Forsk Coding School Knowledge Hub</h1><div class="tj-page-link"><span><a href="<?= htmlspecialchars(site_url('/'),ENT_QUOTES,'UTF-8') ?>">Home</a></span><span><i class="tji-arrow-right-4"></i></span><span>Blog</span></div></div></div></section>
<section class="tj-blog-section section-gap-bottom"><div class="container">
<?php if($page===1 && $q==='' && $category===''): ?><div style="margin-bottom:40px"><h2>Browse 100 technology topic hubs</h2><p>Start with a topic hub rather than a keyword list. Each hub groups the strongest roadmaps, projects, interview preparation and workflow guides for that subject.</p><div class="row rg-20"><?php foreach($hubs as $h): ?><div class="col-lg-4 col-md-6"><article class="blog-item"><div class="blog-content"><div class="blog-meta"><span><?= htmlspecialchars($h['category'],ENT_QUOTES,'UTF-8') ?></span></div><h3 class="blog-title tj-fs-h5"><a href="<?= htmlspecialchars(blog_url($h['slug']),ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($h['title'],ENT_QUOTES,'UTF-8') ?></a></h3><p><?= htmlspecialchars($h['description'],ENT_QUOTES,'UTF-8') ?></p><a class="tj-text-btn" href="<?= htmlspecialchars(blog_url($h['slug']),ENT_QUOTES,'UTF-8') ?>">Explore <?= (int)$h['count'] ?> curated guides <i class="tji-arrow-right-2"></i></a></div></article></div><?php endforeach; ?></div></div><?php endif; ?>
<form method="get" action="<?= htmlspecialchars(blog_url(),ENT_QUOTES,'UTF-8') ?>" class="row rg-20" style="margin-bottom:30px"><div class="col-md-7"><input class="form-control" type="search" name="q" value="<?= htmlspecialchars($q,ENT_QUOTES,'UTF-8') ?>" placeholder="Search curated technology guides"></div><div class="col-md-3"><select class="form-control" name="category"><option value="">All categories</option><?php foreach(array_keys($cats) as $c): ?><option value="<?= htmlspecialchars($c,ENT_QUOTES,'UTF-8') ?>" <?= $category===$c?'selected':'' ?>><?= htmlspecialchars($c,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="tj-btn-primary" type="submit">Search</button></div></form>
<p><strong><?= number_format($total) ?></strong> index-ready and legacy guides found. Page <?= $page ?> of <?= $pages ?>.</p><div class="row rg-30"><?php foreach($slice as $e): $slug=$e['slug']; $fname=$e['image'] ?? ($slug.'.webp'); $disk=__DIR__.'/images/'.$fname; $im=is_file($disk)?blog_image_url($fname):blog_image_url('blog-image-placeholder.svg'); ?><div class="col-lg-4 col-md-6"><article class="blog-item"><div class="blog-thumb"><a href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>"><img src="<?= htmlspecialchars($im,ENT_QUOTES,'UTF-8') ?>" alt="<?= htmlspecialchars($e['title'],ENT_QUOTES,'UTF-8') ?>" loading="lazy"></a></div><div class="blog-content"><div class="blog-meta"><span><?= htmlspecialchars($e['category']??'Technology',ENT_QUOTES,'UTF-8') ?></span></div><h2 class="blog-title tj-fs-h5"><a href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($e['title'],ENT_QUOTES,'UTF-8') ?></a></h2><p><?= htmlspecialchars($e['description']??'',ENT_QUOTES,'UTF-8') ?></p><a class="tj-text-btn" href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>">Read <?= htmlspecialchars($e['subject']??'guide',ENT_QUOTES,'UTF-8') ?> <i class="tji-arrow-right-2"></i></a></div></article></div><?php endforeach; ?></div>
<nav aria-label="Blog pagination" style="margin-top:35px;display:flex;gap:10px;flex-wrap:wrap"><?php if($page>1): ?><a class="tj-btn-primary tj-btn-primary-light" href="?page=<?= $page-1 ?>&q=<?= urlencode($q) ?>&category=<?= urlencode($category) ?>">Previous</a><?php endif; ?><?php if($page<$pages): ?><a class="tj-btn-primary" href="?page=<?= $page+1 ?>&q=<?= urlencode($q) ?>&category=<?= urlencode($category) ?>">Next</a><?php endif; ?></nav>
</div></section></main><?php include $root_path.'/includes/footer.php'; ?></div></div></body></html>
