<?php
$root_path=dirname(__DIR__); require_once $root_path.'/config.php';
$page_title='Forsk Coding School Knowledge Hub | Coding, IT, AI & Career Guides';
$page_description='Explore practical guides on programming, full stack development, data analytics, AI, cloud, cyber security, testing, design and digital marketing from Forsk Coding School Jaipur.';
$page_canonical=seo_url('blog/'); $page_type='website'; $header_variant='header-1';
$page_schema=json_encode(['@context'=>'https://schema.org','@type'=>'CollectionPage','name'=>$page_title,'description'=>$page_description,'url'=>$page_canonical],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
$data=json_decode((string)file_get_contents(__DIR__.'/blog-index.json'),true) ?: [];
$q=trim((string)($_GET['q'] ?? '')); $category=trim((string)($_GET['category'] ?? '')); $page=max(1,(int)($_GET['page'] ?? 1)); $per=30;
if ($q!=='' || $category!=='') $data=array_values(array_filter($data,function($e)use($q,$category){$okq=$q==='' || stripos(($e['title']??'').' '.($e['description']??''),$q)!==false; $okc=$category==='' || strcasecmp($e['category']??'',$category)===0; return $okq&&$okc;}));
$total=count($data); $pages=max(1,(int)ceil($total/$per)); if($page>$pages)$page=$pages; $slice=array_slice($data,($page-1)*$per,$per);
$cats=[]; foreach($data as $e){if(!empty($e['category']))$cats[$e['category']]=true;} ksort($cats);
?><!doctype html><html lang="en"><head><?php include $root_path.'/includes/head.php'; ?></head><body><?php include $root_path.'/includes/header.php'; ?><div id="smooth-wrapper"><div id="smooth-content"><main id="primary" class="site-main"><div class="space-for-header"></div>
<section class="tj-page-header"><div class="container"><div class="tj-page-header-content"><h1 class="tj-page-title">Forsk Coding School Knowledge Hub</h1><div class="tj-page-link"><span><a href="<?= site_url('/') ?>">Home</a></span><span><i class="tji-arrow-right-4"></i></span><span>Blog</span></div></div></div></section>
<section class="tj-blog-section section-gap-bottom"><div class="container"><form method="get" action="<?= htmlspecialchars(blog_url(),ENT_QUOTES,'UTF-8') ?>" class="row rg-20" style="margin-bottom:30px"><div class="col-md-7"><input class="form-control" type="search" name="q" value="<?= htmlspecialchars($q,ENT_QUOTES,'UTF-8') ?>" placeholder="Search 10,000+ technology guides"></div><div class="col-md-3"><select class="form-control" name="category"><option value="">All categories</option><?php foreach(array_keys($cats) as $c): ?><option value="<?= htmlspecialchars($c,ENT_QUOTES,'UTF-8') ?>" <?= $category===$c?'selected':'' ?>><?= htmlspecialchars($c,ENT_QUOTES,'UTF-8') ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="tj-btn-primary" type="submit">Search</button></div></form>
<p><strong><?= number_format($total) ?></strong> guides found. Page <?= $page ?> of <?= $pages ?>.</p><div class="row rg-30"><?php foreach($slice as $e): $slug=$e['slug']; $fname=$e['image'] ?? ($slug.'.webp'); $disk=__DIR__.'/images/'.$fname; $im=is_file($disk)?blog_image_url($fname):blog_image_url('blog-image-placeholder.svg'); ?><div class="col-lg-4 col-md-6"><article class="blog-item"><div class="blog-thumb"><a href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>"><img src="<?= htmlspecialchars($im,ENT_QUOTES,'UTF-8') ?>" alt="<?= htmlspecialchars($e['title'],ENT_QUOTES,'UTF-8') ?>" loading="lazy"></a></div><div class="blog-content"><div class="blog-meta"><span><?= htmlspecialchars($e['category']??'Technology',ENT_QUOTES,'UTF-8') ?></span></div><h2 class="blog-title tj-fs-h5"><a href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>"><?= htmlspecialchars($e['title'],ENT_QUOTES,'UTF-8') ?></a></h2><p><?= htmlspecialchars(substr($e['description']??'',0,170),ENT_QUOTES,'UTF-8') ?></p><a class="tj-text-btn" href="<?= htmlspecialchars(blog_url($slug),ENT_QUOTES,'UTF-8') ?>">Read guide <i class="tji-arrow-right-2"></i></a></div></article></div><?php endforeach; ?></div>
<nav aria-label="Blog pagination" style="margin-top:35px;display:flex;gap:10px;flex-wrap:wrap"><?php if($page>1): ?><a class="tj-btn-primary tj-btn-primary-light" href="?page=<?= $page-1 ?>&q=<?= urlencode($q) ?>&category=<?= urlencode($category) ?>">Previous</a><?php endif; ?><?php if($page<$pages): ?><a class="tj-btn-primary" href="?page=<?= $page+1 ?>&q=<?= urlencode($q) ?>&category=<?= urlencode($category) ?>">Next</a><?php endif; ?></nav>
</div></section></main><?php include $root_path.'/includes/footer.php'; ?></div></div></body></html>
