<?php
return [
    'title' => 'Engineering Colleges in Jaipur',
    'singular' => 'Engineering College',
    'program' => 'B.Tech / Engineering',
    'description' => 'Compare selected engineering colleges in Jaipur using verified official contact links, then request independent admission guidance from Forsk Coding School.',
    'colleges' => [
        [
            'slug' => 'jecrc-foundation',
            'name' => 'Jaipur Engineering College and Research Centre (JECRC Foundation)',
            'short' => 'JECRC Foundation',
            'phone' => '+91 9982682917',
            'website' => 'https://jecrcfoundation.com/',
            'official_page' => 'https://jecrcfoundation.com/',
            'brochure' => 'https://jecrcfoundation.com/wp-content/uploads/2026/02/Final-Handbook-Brochure.pdf',
            'address' => 'Shri Ram ki Nangal, via Sitapura RIICO, Tonk Road, Jaipur 302022',
            'source' => 'https://jecrcfoundation.com/contact-us/',
            'logo_path' => 'engineering-colleges-in-jaipur/assets/logos/jecrc-foundation-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'skit-jaipur',
            'name' => 'Swami Keshvanand Institute of Technology, Management & Gramothan',
            'short' => 'SKIT Jaipur',
            'phone' => '+91 8505003008',
            'website' => 'https://www.skit.ac.in/',
            'official_page' => 'https://www.skit.ac.in/contact-us.html',
            'brochure' => '',
            'address' => 'Ramnagaria, Jagatpura, Jaipur 302017',
            'source' => 'https://www.skit.ac.in/contact-us.html',
            'logo_path' => 'engineering-colleges-in-jaipur/assets/logos/skit-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'poornima-college-of-engineering',
            'name' => 'Poornima College of Engineering',
            'short' => 'Poornima College of Engineering',
            'phone' => '+91 9928555222',
            'website' => 'https://www.poornima.org/',
            'official_page' => 'https://www.poornima.org/admission/btech-at-poornima-group-of-colleges',
            'brochure' => 'https://www.poornima.org/public/uploads/PGCProspectus2026.pdf',
            'address' => 'ISI-6, RIICO Institutional Area, Sitapura, Jaipur 302022',
            'source' => 'https://www.poornima.org/admission/btech-at-poornima-group-of-colleges',
            'logo_path' => 'engineering-colleges-in-jaipur/assets/logos/poornima-college-of-engineering-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'arya-college-of-engineering-it',
            'name' => 'Arya College of Engineering & Information Technology',
            'short' => 'Arya College of Engineering & IT',
            'phone' => '+91 9314881683',
            'website' => 'https://www.aryacollege.in/',
            'official_page' => 'https://www.aryacollege.in/courses/b-tech',
            'brochure' => '',
            'address' => 'SP-42, RIICO Industrial Area, Kukas, Delhi Road, Jaipur 302028',
            'source' => 'https://www.aryacollege.in/contact-us',
            'logo_path' => 'engineering-colleges-in-jaipur/assets/logos/arya-college-of-engineering-it-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'anand-international-college-of-engineering',
            'name' => 'Anand International College of Engineering',
            'short' => 'Anand-ICE',
            'phone' => '+91 9928755552',
            'website' => 'https://anandice.ac.in/',
            'official_page' => 'https://anandice.ac.in/',
            'brochure' => '',
            'address' => 'Near Kanota, Agra Road, Jaipur 303012',
            'source' => 'https://anandice.ac.in/',
            'logo_path' => 'engineering-colleges-in-jaipur/assets/logos/anand-international-college-of-engineering-logo.webp',
            'verified_on' => '2026-09-13',
        ],
    ],
    'slug' => 'engineering-colleges-in-jaipur',
];
