<?php
/**
 * Forsk Coding School course catalogue.
 *
 * Keep public course discovery data in one place so the catalogue can stay
 * factual, searchable and easy to maintain without repeating template markup.
 * Do not add ratings, learner counts, pricing or duration here unless the value
 * is verified and maintained as an authoritative business fact.
 */

return [
    ['slug' => 'python-programming-course-jaipur.php', 'name' => 'Python Programming Course', 'category' => 'Programming'],
    ['slug' => 'java-programming-course-jaipur.php', 'name' => 'Java Programming Course', 'category' => 'Programming'],
    ['slug' => 'c-programming-course-jaipur.php', 'name' => 'C Programming Course', 'category' => 'Programming'],
    ['slug' => 'c-plus-plus-course-jaipur.php', 'name' => 'C++ Course', 'category' => 'Programming'],
    ['slug' => 'c-sharp-course-jaipur.php', 'name' => 'C# Course', 'category' => 'Programming'],
    ['slug' => 'javascript-course-jaipur.php', 'name' => 'JavaScript Course', 'category' => 'Programming'],
    ['slug' => 'php-course-jaipur.php', 'name' => 'PHP Course', 'category' => 'Programming'],
    ['slug' => 'full-stack-development-course-jaipur.php', 'name' => 'Full Stack Development Course', 'category' => 'Full Stack'],
    ['slug' => 'mern-stack-course-jaipur.php', 'name' => 'MERN Stack Course', 'category' => 'Full Stack'],
    ['slug' => 'mean-stack-course-jaipur.php', 'name' => 'MEAN Stack Course', 'category' => 'Full Stack'],
    ['slug' => 'java-full-stack-course-jaipur.php', 'name' => 'Java Full Stack Course', 'category' => 'Full Stack'],
    ['slug' => 'python-full-stack-course-jaipur.php', 'name' => 'Python Full Stack Course', 'category' => 'Full Stack'],
    ['slug' => 'dotnet-full-stack-course-jaipur.php', 'name' => '.NET Full Stack Course', 'category' => 'Full Stack'],
    ['slug' => 'react-js-course-jaipur.php', 'name' => 'React.js Course', 'category' => 'Web Development'],
    ['slug' => 'angular-course-jaipur.php', 'name' => 'Angular Course', 'category' => 'Web Development'],
    ['slug' => 'node-js-course-jaipur.php', 'name' => 'Node.js Course', 'category' => 'Web Development'],
    ['slug' => 'next-js-course-jaipur.php', 'name' => 'Next.js Course', 'category' => 'Web Development'],
    ['slug' => 'core-java-course-jaipur.php', 'name' => 'Core Java Course', 'category' => 'Java'],
    ['slug' => 'advanced-java-course-jaipur.php', 'name' => 'Advanced Java Course', 'category' => 'Java'],
    ['slug' => 'jdbc-course-jaipur.php', 'name' => 'JDBC Course', 'category' => 'Java'],
    ['slug' => 'servlets-jsp-course-jaipur.php', 'name' => 'Servlets & JSP Course', 'category' => 'Java'],
    ['slug' => 'spring-framework-course-jaipur.php', 'name' => 'Spring Framework Course', 'category' => 'Java'],
    ['slug' => 'spring-boot-course-jaipur.php', 'name' => 'Spring Boot Course', 'category' => 'Java'],
    ['slug' => 'spring-mvc-course-jaipur.php', 'name' => 'Spring MVC Course', 'category' => 'Java'],
    ['slug' => 'hibernate-course-jaipur.php', 'name' => 'Hibernate Course', 'category' => 'Java'],
    ['slug' => 'jpa-course-jaipur.php', 'name' => 'JPA Course', 'category' => 'Java'],
    ['slug' => 'java-microservices-course-jaipur.php', 'name' => 'Java Microservices Course', 'category' => 'Java'],
    ['slug' => 'java-rest-api-course-jaipur.php', 'name' => 'Java REST API Course', 'category' => 'Java'],
    ['slug' => 'java-design-patterns-course-jaipur.php', 'name' => 'Java Design Patterns Course', 'category' => 'Java'],
    ['slug' => 'java-multithreading-course-jaipur.php', 'name' => 'Java Multithreading Course', 'category' => 'Java'],
    ['slug' => 'java-testing-course-jaipur.php', 'name' => 'Java Testing Course', 'category' => 'Java'],
    ['slug' => 'helidon-course-jaipur.php', 'name' => 'Helidon Course', 'category' => 'Java'],
    ['slug' => 'big-data-java-course-jaipur.php', 'name' => 'Big Data with Java Course', 'category' => 'Java'],
    ['slug' => 'hadoop-course-jaipur.php', 'name' => 'Hadoop Course', 'category' => 'Data & AI'],
    ['slug' => 'kafka-java-course-jaipur.php', 'name' => 'Kafka with Java Course', 'category' => 'Java'],
    ['slug' => 'java-interview-preparation-jaipur.php', 'name' => 'Java Interview Preparation', 'category' => 'Java'],
    ['slug' => 'data-science-course-jaipur.php', 'name' => 'Data Science Course', 'category' => 'Data & AI'],
    ['slug' => 'data-analytics-course-jaipur.php', 'name' => 'Data Analytics Course', 'category' => 'Data & AI'],
    ['slug' => 'business-analytics-course-jaipur.php', 'name' => 'Business Analytics Course', 'category' => 'Data & AI'],
    ['slug' => 'machine-learning-course-jaipur.php', 'name' => 'Machine Learning Course', 'category' => 'Data & AI', 'image' => 'assets/images/machine_learning_course_banner.webp'],
    ['slug' => 'artificial-intelligence-course-jaipur.php', 'name' => 'Artificial Intelligence Course', 'category' => 'Data & AI'],
    ['slug' => 'generative-ai-course-jaipur.php', 'name' => 'Generative AI Course', 'category' => 'Data & AI'],
    ['slug' => 'power-bi-course-jaipur.php', 'name' => 'Power BI Course', 'category' => 'Data & AI'],
    ['slug' => 'sql-course-jaipur.php', 'name' => 'SQL Course', 'category' => 'Data & AI'],
    ['slug' => 'advanced-excel-course-jaipur.php', 'name' => 'Advanced Excel Course', 'category' => 'Data & AI'],
    ['slug' => 'ai-tools-course-jaipur.php', 'name' => 'AI Tools Course', 'category' => 'Data & AI'],
    ['slug' => 'cloud-computing-course-jaipur.php', 'name' => 'Cloud Computing Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'aws-course-jaipur.php', 'name' => 'AWS Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'azure-course-jaipur.php', 'name' => 'Azure Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'google-cloud-course-jaipur.php', 'name' => 'Google Cloud Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'devops-course-jaipur.php', 'name' => 'DevOps Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'docker-course-jaipur.php', 'name' => 'Docker Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'kubernetes-course-jaipur.php', 'name' => 'Kubernetes Course', 'category' => 'Cloud & DevOps'],
    ['slug' => 'cyber-security-course-jaipur.php', 'name' => 'Cyber Security Course', 'category' => 'Cyber Security'],
    ['slug' => 'ethical-hacking-course-jaipur.php', 'name' => 'Ethical Hacking Course', 'category' => 'Cyber Security'],
    ['slug' => 'ceh-course-jaipur.php', 'name' => 'CEH Course', 'category' => 'Cyber Security'],
    ['slug' => 'soc-analyst-course-jaipur.php', 'name' => 'SOC Analyst Course', 'category' => 'Cyber Security'],
    ['slug' => 'penetration-testing-course-jaipur.php', 'name' => 'Penetration Testing Course', 'category' => 'Cyber Security'],
    ['slug' => 'network-security-course-jaipur.php', 'name' => 'Network Security Course', 'category' => 'Cyber Security'],
    ['slug' => 'software-testing-course-jaipur.php', 'name' => 'Software Testing Course', 'category' => 'Software Testing'],
    ['slug' => 'manual-testing-course-jaipur.php', 'name' => 'Manual Testing Course', 'category' => 'Software Testing'],
    ['slug' => 'automation-testing-course-jaipur.php', 'name' => 'Automation Testing Course', 'category' => 'Software Testing'],
    ['slug' => 'selenium-course-jaipur.php', 'name' => 'Selenium Course', 'category' => 'Software Testing'],
    ['slug' => 'api-testing-course-jaipur.php', 'name' => 'API Testing Course', 'category' => 'Software Testing'],
    ['slug' => 'playwright-course-jaipur.php', 'name' => 'Playwright Course', 'category' => 'Software Testing'],
    ['slug' => 'digital-marketing-course-jaipur.php', 'name' => 'Digital Marketing Course', 'category' => 'Digital Marketing'],
    ['slug' => 'seo-course-jaipur.php', 'name' => 'SEO Course', 'category' => 'Digital Marketing'],
    ['slug' => 'google-ads-course-jaipur.php', 'name' => 'Google Ads Course', 'category' => 'Digital Marketing'],
    ['slug' => 'social-media-marketing-course-jaipur.php', 'name' => 'Social Media Marketing Course', 'category' => 'Digital Marketing'],
    ['slug' => 'content-marketing-course-jaipur.php', 'name' => 'Content Marketing Course', 'category' => 'Digital Marketing'],
    ['slug' => 'email-marketing-course-jaipur.php', 'name' => 'Email Marketing Course', 'category' => 'Digital Marketing'],
    ['slug' => 'ui-ux-design-course-jaipur.php', 'name' => 'UI/UX Design Course', 'category' => 'Design'],
    ['slug' => 'figma-course-jaipur.php', 'name' => 'Figma Course', 'category' => 'Design'],
    ['slug' => 'graphic-design-course-jaipur.php', 'name' => 'Graphic Design Course', 'category' => 'Design'],
    ['slug' => 'mobile-app-development-course-jaipur.php', 'name' => 'Mobile App Development Course', 'category' => 'Mobile Development'],
    ['slug' => 'android-course-jaipur.php', 'name' => 'Android Development Course', 'category' => 'Mobile Development'],
    ['slug' => 'kotlin-course-jaipur.php', 'name' => 'Kotlin Course', 'category' => 'Mobile Development'],
    ['slug' => 'flutter-course-jaipur.php', 'name' => 'Flutter Course', 'category' => 'Mobile Development'],
    ['slug' => 'react-native-course-jaipur.php', 'name' => 'React Native Course', 'category' => 'Mobile Development'],
    ['slug' => 'ios-app-development-course-jaipur.php', 'name' => 'iOS App Development Course', 'category' => 'Mobile Development'],
    ['slug' => 'networking-course-jaipur.php', 'name' => 'Networking Course', 'category' => 'Networking'],
    ['slug' => 'ccna-course-jaipur.php', 'name' => 'CCNA Course', 'category' => 'Networking'],
    ['slug' => 'ccnp-course-jaipur.php', 'name' => 'CCNP Course', 'category' => 'Networking'],
    ['slug' => 'linux-course-jaipur.php', 'name' => 'Linux Course', 'category' => 'Networking'],
    ['slug' => 'windows-server-course-jaipur.php', 'name' => 'Windows Server Course', 'category' => 'Networking'],
    ['slug' => 'diploma-programs-jaipur.php', 'name' => 'Diploma Programs', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-full-stack-development-jaipur.php', 'name' => 'Diploma in Full Stack Development', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-data-science-ai-jaipur.php', 'name' => 'Diploma in Data Science & AI', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-python-programming-jaipur.php', 'name' => 'Diploma in Python Programming', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-java-programming-jaipur.php', 'name' => 'Diploma in Java Programming', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-digital-marketing-jaipur.php', 'name' => 'Diploma in Digital Marketing', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-cyber-security-jaipur.php', 'name' => 'Diploma in Cyber Security', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-cloud-computing-jaipur.php', 'name' => 'Diploma in Cloud Computing', 'category' => 'Diploma Programs'],
    ['slug' => 'diploma-data-analytics-jaipur.php', 'name' => 'Diploma in Data Analytics', 'category' => 'Diploma Programs'],
    ['slug' => 'internship-programs-jaipur.php', 'name' => 'Internship Programs', 'category' => 'Training & Internship'],
    ['slug' => 'summer-internship-jaipur.php', 'name' => 'Summer Internship', 'category' => 'Training & Internship'],
    ['slug' => 'winter-internship-jaipur.php', 'name' => 'Winter Internship', 'category' => 'Training & Internship'],
    ['slug' => 'industrial-training-jaipur.php', 'name' => 'Industrial Training', 'category' => 'Training & Internship'],
    ['slug' => 'live-project-training-jaipur.php', 'name' => 'Live Project Training', 'category' => 'Training & Internship'],
    ['slug' => 'final-year-projects-jaipur.php', 'name' => 'Final Year Projects', 'category' => 'Training & Internship'],
    ['slug' => 'corporate-training-jaipur.php', 'name' => 'Corporate Training', 'category' => 'Training & Internship'],
    ['slug' => 'personality-development-course-jaipur.php', 'name' => 'Personality Development Course', 'category' => 'Career Skills'],
    ['slug' => 'other-it-courses-jaipur.php', 'name' => 'Other IT Courses', 'category' => 'IT Courses'],
];
