<?php
return [
    'title' => 'MCA Colleges in Jaipur',
    'singular' => 'MCA College',
    'program' => 'MCA',
    'description' => 'Explore selected MCA colleges and universities in Jaipur with verified official contact links and request admission guidance from Forsk Coding School.',
    'colleges' => [
        [
            'slug' => 'jecrc-university',
            'name' => 'JECRC University',
            'short' => 'JECRC University',
            'phone' => '+91 9773368851',
            'website' => 'https://jecrcuniversity.edu.in/',
            'official_page' => 'https://jecrcuniversity.edu.in/',
            'brochure' => '',
            'address' => 'Ramchandrapura Industrial Area, Vidhani, Sitapura Extension, Jaipur 303905',
            'source' => 'https://jecrcuniversity.edu.in/contact-us/',
            'logo_path' => 'mca-colleges-in-jaipur/assets/logos/jecrc-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'jaipur-national-university',
            'name' => 'Jaipur National University',
            'short' => 'Jaipur National University',
            'phone' => '1800 102 1900',
            'website' => 'https://www.jnujaipur.ac.in/',
            'official_page' => 'https://www.jnujaipur.ac.in/programmes/pg-programmes/mca-master-of-computer-application',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan',
            'source' => 'https://www.jnujaipur.ac.in/programmes/pg-programmes/mca-master-of-computer-application',
            'logo_path' => 'mca-colleges-in-jaipur/assets/logos/jaipur-national-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'manipal-university-jaipur',
            'name' => 'Manipal University Jaipur',
            'short' => 'Manipal University Jaipur',
            'phone' => '1800 102 0128',
            'website' => 'https://jaipur.manipal.edu/',
            'official_page' => 'https://jaipur.manipal.edu/admission-contact.php',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan',
            'source' => 'https://jaipur.manipal.edu/admission-contact.php',
            'logo_path' => 'mca-colleges-in-jaipur/assets/logos/manipal-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'poornima-university',
            'name' => 'Poornima University',
            'short' => 'Poornima University',
            'phone' => '+91 8875666618',
            'website' => 'https://www.poornima.edu.in/',
            'official_page' => 'https://www.poornima.edu.in/admissions/pg/faculty-of-computer-science-and-engineering/mca-cyber-security/',
            'brochure' => '',
            'address' => 'Ramchandrapura, Vidhani Vatika, Sitapura Extension, Jaipur 303905',
            'source' => 'https://www.poornima.edu.in/admissions/pg/faculty-of-computer-science-and-engineering/mca-cyber-security/',
            'logo_path' => 'mca-colleges-in-jaipur/assets/logos/poornima-university-logo.webp',
            'verified_on' => '2026-09-13',
        ],
        [
            'slug' => 'apex-university-jaipur',
            'name' => 'Apex University Jaipur',
            'short' => 'Apex University Jaipur',
            'phone' => '+91 7413874138',
            'website' => 'https://www.apexuniversity.co.in/',
            'official_page' => 'https://www.apexuniversity.co.in/course/mca',
            'brochure' => '',
            'address' => 'Jaipur, Rajasthan 303002',
            'source' => 'https://www.apexuniversity.co.in/course/mca',
            'logo_path' => 'mca-colleges-in-jaipur/assets/logos/apex-university-jaipur-logo.webp',
            'verified_on' => '2026-09-13',
        ],
    ],
    'slug' => 'mca-colleges-in-jaipur',
];
